### ISSUE TITLE
gmodule-no-export-2.0.pc (from glib) is missing

### ISSUE THREAD

**Issue by SimonSapin** [servo/libgstreamer_android_gen#3]
In an effort to reduce the size of Docker images used for various tasks on Taskcluster, I’ve tried building Servo for Android in an container with Ubuntu packages for gstreamer. I *think* they shouldn’t be needed, since we’re using gstreamer from this repository instead. However, the build fails:

```
error: failed to run custom build command for `gstreamer-sys v0.6.0`
process didn't exit successfully: `/repo/target/debug/build/gstreamer-sys-73789ff24e121638/build-script-build` (exit code: 1)
--- stderr
`"pkg-config" "--libs" "--cflags" "gstreamer-1.0 >= 1.12"` did not exit successfully: exit code: 1
--- stderr
Package gmodule-no-export-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gmodule-no-export-2.0.pc'
to the PKG_CONFIG_PATH environment variable
Package 'gmodule-no-export-2.0', required by 'gstreamer-1.0', not found


warning: build failed, waiting for other jobs to finish...
error: build failed
```

Indeed, `gmodule-no-export-2.0.pc` is not present `target/gstreamer/gst-build-armeabi-v7a/pkgconfig/` (although 112 other `.pc` files are). In Ubuntu, `/usr/lib/x86_64-linux-gnu/pkgconfig/gmodule-no-export-2.0.pc` is owned by the `libglib2.0-dev` package.

CC @ferjm

**Comment by ferjm** [comment]
> I think they shouldn’t be needed, since we’re using gstreamer from this repository instead.

Indeed, they shouldn't be needed.

Is it possible that you are using the pkgconfig info from Ubuntu packages instead of `libgstreamer_android`? How does your PKG_CONFIG_PATH look like? Could you get the output of `pkg-config --libs --cflags gstreamer-1.0` during the build process?

**Comment by ferjm** [comment]
CC @sdroege

**Comment by sdroege** [comment]
Which .pc file has `gmodule-no-export-2.0` in its `Requires:` line?

**Comment by ferjm** [comment]
They are all in `Requires.private` for the Android binaries.
```
❯ grep -rni gmodule-no-export .
./gio-2.0.pc:15:Requires.private: gmodule-no-export-2.0
./gstreamer-1.0.pc:16:Requires.private: gmodule-no-export-2.0
./gdk-pixbuf-2.0.pc:15:Requires.private: gmodule-no-export-2.0 libpng16
```

**Comment by sdroege** [comment]
So the question is why this pkg-config file does not exist :)

**Comment by ferjm** [comment]
Ugh, yeah, we are missing 3 .pc files (`gmodule-export-2.0`, `gmodule-no-export-2.0` and `gst-editing-services-1.0`). And I know why: we are naively [removing](https://github.com/servo/libgstreamer_android_gen/blob/master/build.sh#L43) the `-e` files generated by `sed`. I'll try to fix it and generate new binaries along day.

What I don't really understand is why this is currently working for Servo and servo-media builds... It seems that the only dependency of the three missing ones that appears in the remaining .pc files is `gmodule-no-export-2.0` and, as I said before, it is listed only in the `Requires.private` section. I don't really know the difference between `Requires` and `Requires.private`, but I guess being in the .private section may be the reason why it is not being required during Servo's build(?).

**Comment by SimonSapin** [comment]
I believe Servo’s builds rely on finding this file from system packages, e.g. in `/usr/lib/x86_64-linux-gnu/pkgconfig/gmodule-no-export-2.0.pc`.

If you have Docker available, an easy way to reproduce is to pipe the file below into `docker run -`. It’ll take a while to download everything, but Docker’s build cache means you don’t need to run successful unchanged commands again. However this doesn’t provide as-is an easy way to make changes to the Servo repo and try them.

```Dockerfile
FROM ubuntu:bionic-20180821

RUN \
    apt-get update -q && \
    apt-get install -qy --no-install-recommends \
        git \
        ca-certificates \
        python \
        virtualenv \
        curl \
        g++ \
        openjdk-8-jdk-headless \
        pkg-config \
    && \
    curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain none -y

ENV PATH="/root/.cargo/bin:$PATH"

RUN git clone --depth 1 https://github.com/servo/servo /repo
WORKDIR /repo
RUN yes | ./mach bootstrap-android
RUN ./mach build --no-package --dev --android -p libc # cache dependency downloads etc.
RUN ./mach build --no-package --dev --android -p gstreamer-sys
```
