### ISSUE TITLE
Can't build with Gstreamer 1.18.0 and current NDK

### ISSUE THREAD

**Issue by veitk** [servo/libgstreamer_android_gen#9]
Mac OS Catalina / NDK 21.6

=== Building GStreamer 1.18.0 for target armv7 with jni/armv7.mk ===
/Users/vkoettin/Library/Android/sdk/ndk-bundle/build/core/build-binary.mk:651: Android NDK: Module gstreamer_for_android depends on undefined modules: gstreamer_android
jni/Android.mk:32: /Users/vkoettin/Android/gestreamer/armv7/share/gst-android/ndk-build//gstreamer-1.0.mk: No such file or directory
make: *** No rule to make target '/Users/vkoettin/Android/gestreamer/armv7/share/gst-android/ndk-build//gstreamer-1.0.mk'.  Stop.
cp: libs/armeabi-v7a/libgstreamer_android.so: No such file or directory
cp: /Users/vkoettin/Android/gestreamer/armv7/lib/pkgconfig: No such file or directory
Processing gst-build-armeabi-v7a
./build.sh: line 40: cd: gst-build-armeabi-v7a: No such file or directory
sed: pkgconfig/*: No such file or directory
sed: pkgconfig/*: No such file or directory
sed: pkgconfig/*: No such file or directory
sed: pkgconfig/*: No such file or directory
	zip warning: name not matched: gst-build-armeabi-v7a/*

zip error: Nothing to do! (try: zip -v -r out/gstreamer-armeabi-v7a-1.18.0-20201007-134933.zip . -i gst-build-armeabi-v7a/*)
	zip warning: name not matched: gst-build-armeabi-v7a/*

zip error: Nothing to do! (try: zip -v -r out/gst-build-armeabi-v7a.zip . -i gst-build-armeabi-v7a/*)

**Comment by jdm** [comment]
This is unsurprising. The last NDK that was supported was v15, iirc.
